WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7fb16d317400>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '36bde1bd-b2f6-4c93-b54a-87ad00ebfde6'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '36bde1bd-b2f6-4c93-b54a-87ad00ebfde6'}}
WARNING  celery.redirected:log.py:227 [2021-05-31 18:54:18,313] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '36bde1bd-b2f6-4c93-b54a-87ad00ebfde6'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:36bde1bd-b2f6-4c93-b54a-87ad00ebfde6
DEBUG    root:mylogger.py:80 token:36bde1bd-b2f6-4c93-b54a-87ad00ebfde6
WARNING  celery.redirected:log.py:227 [2021-05-31 18:54:18,315] | mylogger.py |DEBUG : token:36bde1bd-b2f6-4c93-b54a-87ad00ebfde6
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:36bde1bd-b2f6-4c93-b54a-87ad00ebfde6
DEBUG    root:mylogger.py:80 token:36bde1bd-b2f6-4c93-b54a-87ad00ebfde6
WARNING  celery.redirected:log.py:227 [2021-05-31 18:54:18,317] | mylogger.py |DEBUG : token:36bde1bd-b2f6-4c93-b54a-87ad00ebfde6