WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7f972ba35c88>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '066fe6e0-3ef4-4c42-a950-060c121abe2c'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': '066fe6e0-3ef4-4c42-a950-060c121abe2c'}}
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,217] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': '066fe6e0-3ef4-4c42-a950-060c121abe2c'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:066fe6e0-3ef4-4c42-a950-060c121abe2c
DEBUG    root:mylogger.py:80 token:066fe6e0-3ef4-4c42-a950-060c121abe2c
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,218] | mylogger.py |DEBUG : token:066fe6e0-3ef4-4c42-a950-060c121abe2c
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:066fe6e0-3ef4-4c42-a950-060c121abe2c
DEBUG    root:mylogger.py:80 token:066fe6e0-3ef4-4c42-a950-060c121abe2c
WARNING  celery.redirected:log.py:227 [2021-05-31 18:51:12,220] | mylogger.py |DEBUG : token:066fe6e0-3ef4-4c42-a950-060c121abe2c