WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:客诉工单列表,当前责任是本人-待处理
INFO     root:mylogger.py:78 case用例:客诉工单列表,当前责任是本人-待处理
WARNING  celery.redirected:log.py:227 [2021-05-31 18:38:31,872] | mylogger.py |INFO  : case用例:客诉工单列表,当前责任是本人-待处理
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderList
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/workOrderList
WARNING  celery.redirected:log.py:227 [2021-05-31 18:38:31,873] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/workOrderList
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：fa4bac6a-0e42-4a6f-90eb-c355ca25c0ba
INFO     root:mylogger.py:78 token：fa4bac6a-0e42-4a6f-90eb-c355ca25c0ba
WARNING  celery.redirected:log.py:227 [2021-05-31 18:38:31,874] | mylogger.py |INFO  : token：fa4bac6a-0e42-4a6f-90eb-c355ca25c0ba
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer fa4bac6a-0e42-4a6f-90eb-c355ca25c0ba', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :get
WARNING  celery.redirected:log.py:227 pararm :{"page":1,"size":2,"status":1}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 get 请求 ....
DEBUG    root:mylogger.py:80 get 请求 ....
WARNING  celery.redirected:log.py:227 [2021-05-31 18:38:31,875] | mylogger.py |DEBUG : get 请求 ....
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderList?page=1&size=2&status=1 HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "GET /bp/workOrderList?page=1&size=2&status=1 HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': 0, 'data': [{'id': 2, 'type': 1, 'stationId': 100212, 'details': 'wqweqweq', 'phone': '', 'status': 1, 'createTime': '2021-05-12 15:40:44', 'createUser': 304851520, 'currentUser': 62, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '黄敏'}, {'id': 3, 'type': 1, 'stationId': 100212, 'details': 'asdfvxcvxcvxc', 'phone': '', 'status': 1, 'createTime': '2021-05-12 15:40:58', 'createUser': 304851520, 'currentUser': 862885, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '志雄BP'}]}
DEBUG    root:mylogger.py:80 测试结果:get,,,{'errorCode': 0, 'data': [{'id': 2, 'type': 1, 'stationId': 100212, 'details': 'wqweqweq', 'phone': '', 'status': 1, 'createTime': '2021-05-12 15:40:44', 'createUser': 304851520, 'currentUser': 62, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '黄敏'}, {'id': 3, 'type': 1, 'stationId': 100212, 'details': 'asdfvxcvxcvxc', 'phone': '', 'status': 1, 'createTime': '2021-05-12 15:40:58', 'createUser': 304851520, 'currentUser': 862885, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '志雄BP'}]}
WARNING  celery.redirected:log.py:227 [2021-05-31 18:38:32,016] | mylogger.py |DEBUG : 测试结果:get,,,{'errorCode': 0, 'data': [{'id': 2, 'type': 1, 'stationId': 100212, 'details': 'wqweqweq', 'phone': '', 'status': 1, 'createTime': '2021-05-12 15:40:44', 'createUser': 304851520, 'currentUser': 62, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '黄敏'}, {'id': 3, 'type': 1, 'stationId': 100212, 'details': 'asdfvxcvxcvxc', 'phone': '', 'status': 1, 'createTime': '2021-05-12 15:40:58', 'createUser': 304851520, 'currentUser': 862885, 'createUserName': '志雄BP', 'stationName': '老虎岭', 'latestOperator': '志雄BP'}]}
WARNING  celery.redirected:log.py:227 get 请求结束。。。。。。