WARNING  celery.redirected:log.py:227 ^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^^--2--^
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 case用例:修改银行卡信息
INFO     root:mylogger.py:78 case用例:修改银行卡信息
WARNING  celery.redirected:log.py:227 [2021-05-24 15:21:42,146] | mylogger.py |INFO  : case用例:修改银行卡信息
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/modifyBankInfo
INFO     root:mylogger.py:78 地址url：https://test.xlvren.com/bp/modifyBankInfo
WARNING  celery.redirected:log.py:227 [2021-05-24 15:21:42,148] | mylogger.py |INFO  : 地址url：https://test.xlvren.com/bp/modifyBankInfo
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 INFO     root:mylogger.py:78 token：037f24e0-d26a-4895-9bbb-67cec4c5ed2a
INFO     root:mylogger.py:78 token：037f24e0-d26a-4895-9bbb-67cec4c5ed2a
WARNING  celery.redirected:log.py:227 [2021-05-24 15:21:42,150] | mylogger.py |INFO  : token：037f24e0-d26a-4895-9bbb-67cec4c5ed2a
WARNING  celery.redirected:log.py:227 header :{'Authorization': 'Bearer 037f24e0-d26a-4895-9bbb-67cec4c5ed2a', 'Content-Type': 'application/json'}
WARNING  celery.redirected:log.py:227 method :post
WARNING  celery.redirected:log.py:227 pararm :{
 "bank": "中国银行",
 "bankAccount": "64645456466464546",
 "bankUserName": "啦啦啦小魔法"
}
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 post 请求...
DEBUG    root:mylogger.py:80 post 请求...
WARNING  celery.redirected:log.py:227 [2021-05-24 15:21:42,153] | mylogger.py |DEBUG : post 请求...
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:975 Starting new HTTPS connection (1): test.xlvren.com:443
WARNING  celery.redirected:log.py:227 DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/modifyBankInfo HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:461 https://test.xlvren.com:443 "POST /bp/modifyBankInfo HTTP/1.1" 200 None
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
DEBUG    root:mylogger.py:80 `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 [2021-05-24 15:21:42,348] | mylogger.py |DEBUG : `````````````````````````````````````````````````
WARNING  celery.redirected:log.py:227 post 请求 结束。。。。。