WARNING  celery.redirected:log.py:227 ---------------token---------------------
WARNING  celery.redirected:log.py:227 <configparser.ConfigParser object at 0x7f9537930a90>
WARNING  celery.redirected:log.py:227 https://test.xlvren.com/bp/login
WARNING  celery.redirected:log.py:227 ---------------headers---------------------
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': 'dbd11cf3-749f-46b6-b3d1-9c761b04d023'}}
ERROR    root:mylogger.py:84 测试结果:{'errorCode': 0, 'data': {'token': 'dbd11cf3-749f-46b6-b3d1-9c761b04d023'}}
WARNING  celery.redirected:log.py:227 [2021-06-01 09:34:45,318] | mylogger.py |ERROR : 测试结果:{'errorCode': 0, 'data': {'token': 'dbd11cf3-749f-46b6-b3d1-9c761b04d023'}}
WARNING  celery.redirected:log.py:227 **************************************************
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:dbd11cf3-749f-46b6-b3d1-9c761b04d023
DEBUG    root:mylogger.py:80 token:dbd11cf3-749f-46b6-b3d1-9c761b04d023
WARNING  celery.redirected:log.py:227 [2021-06-01 09:34:45,320] | mylogger.py |DEBUG : token:dbd11cf3-749f-46b6-b3d1-9c761b04d023
WARNING  celery.redirected:log.py:227 log_dir:../logs
WARNING  celery.redirected:log.py:227 folder exist!
WARNING  celery.redirected:log.py:227 DEBUG    root:mylogger.py:80 token:dbd11cf3-749f-46b6-b3d1-9c761b04d023
DEBUG    root:mylogger.py:80 token:dbd11cf3-749f-46b6-b3d1-9c761b04d023
WARNING  celery.redirected:log.py:227 [2021-06-01 09:34:45,321] | mylogger.py |DEBUG : token:dbd11cf3-749f-46b6-b3d1-9c761b04d023